### ISSUE TITLE
Probable wrong variable check in VitamFieldsHelper

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#120]
https://github.com/ProgrammeVitam/vitam/blob/0f98e57746c79c5a225a5b9526b8109973c84ee1/sources/common/common-database-vitam/common-database-public/src/main/java/fr/gouv/vitam/common/database/builder/query/VitamFieldsHelper.java#L379

Should it be: `hashVersion` instead computed just before?

**Comment by TDevillechabrolle** [comment]
You are right Frédéric.
The issue is forwaded to development team
Thierry

**Comment by GiooDev** [comment]
Thanks for your feedback.

It will be fixed on the next release of Vitam.
