### ISSUE TITLE
Lancement de Ingest External en mode 'dummy'

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#14]
Bonjour,
Mon scénario est le suivant:
- avoir un Ingest External fonctionnel, hormis que le reste (Ingest Internal et suivant) seraient des "fakes"
- l'objectif est d'avoir une plateforme simple et très légère de tests pour s'interfacer en mode "client" avec Ingest External

Quel est selon vous la meilleure approche ?
- Je pensais utiliser un rpm/deb Ingest External et le lancer
- Créer un fake Ingest Internal et Workspace et ... (selon les autres dépendances)
Mais cela me semble un peu compliqué.

Du coup, j'opterais pour un lancement plus simple :
- Depuis le code source de Ingest External, en utilisant les clients internal fake (et en permettant des valeurs plus utiles pour les tests), un peu à la mode Junit...

Un conseil ? Des recommandations ?
Bien à vous,
Frédéric

**Comment by gansheer** [comment]
Bonjour,

En l'état actuel de VITAM il n'est pas prévu de pouvoir lancer uniquement un module (même external) fonctionnel. Vitam nécessite, dans son architecture actuelle, d'avoir tous les modules non-extra disponibles.

De plus il ne nous a pas semblé pertinent d'entretenir un jeu de données dans les clients java des modules internes de type 'mock'. Il n'est donc pas conseillé à ce jour de se baser dessus. En outre pour les nouvelles fonctionnalités l'utilisation du mock renvoie une Exception.

Nous préconisons donc d'utiliser une des atlternatives permettant l'utilisation d'une instance VITAM de test fournis par Vitam :
* installation d'un VITAM orienté développement (https://github.com/ProgrammeVitam/vitam#deploiement-sur-poste-de-developpement)
* la VM de demo mise à disposition (https://www.programmevitam.fr/pages/ressources/)

Il reste tout à fait possible de lancer un serveur Ingest External à partir du code pour du test rapide sans configurer les clients. Par contre la cohérence des données fournies par les 'mock' n'est pas garantie, et il faudra donc les modifier. Et l'absence des outils comme l'antivirus et le Siegfried risquent de poser problème. 
Des exemples de configuration de développement sont fournis dans le dossier `vitam-conf-dev` des sources.

Bien cordialement,
Gaëlle Fournier

**Comment by fredericBregier** [comment]
Merci,
Je vais donc essayer la VM de démo (la procédure orienté développement n'a pas fonctionné sur mon Ubuntu...).
Je clos cette demande ;-)
