### ISSUE TITLE
Erreur dans le script lors de l'installation des packages rpm dédiés

### ISSUE THREAD

**Issue by mathislef34** [ProgrammeVitam/vitam#159]
Bonjour,

Dans la documentation, il nous est indiqué : 

Pour construire les packages rpm dédiés : 
./rpm/vitam-product/build-all.sh

Cependant, quand j'exécute cette commande, voici la sortie que j'obtiens : 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/116552541/227490363-07e0d2ac-2f2d-4591-b45c-e4efed04613e.png">

"./rpm/vitam-product/build.sh: line 99: spectool: command not found"

Pouvez-vous m'aider ?

**Comment by TDevillechabrolle** [comment]
Bonjour Mathis,

Nous allons regarder cela.
En attendant, si vous le souhaitez, vous pouvez utiliser notre dépôt de binaires prépackagés:
https://download.programmevitam.fr/vitam_repository/

**Comment by mathislef34** [comment]
Très bien merci.

**Comment by GiooDev** [comment]
Bonjour,

Vu l'ancienneté du ticket et la solution alternatives proposée, nous clôturons le ticket.

N'hésitez pas à ouvrir un nouveau ticket si vous rencontrez de nouveaux problèmes.
