### ISSUE TITLE
Question sur l'ingest et son asynchronicité

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#16]
Bonjour,
Selon l'API REST, la procédure d'ingest serait la suivante:

- POST file ou fileLocal sur /ingests, qui retourne via Header le X-Request-ID
- Il retourne aussi X-Global-Execution-State = PAUSE et X-Global-Execution-Status = UNKNOWN

Ainsi, seul l'ID de l'Ingest est fourni en retour, mais pas son ATR.
Pour obtenir l'ATR, il faut faire:
- GET /ingests/{objectId}/archivetransferreply où ObjectId est l'Id précédemment reçu

Mais là vient la question:
- Si le traitement est terminé, on obtient un 200 et le ATR dans le body : ok
- Si le traitement n'est pas terminé, qu'est-ce qu'on obtient ? 404 ? 4XX ? 5XX ? Coment gère-t-on la durée longue du traitement côté versant ? Existe-t-il un mécanisme de pooling ?

Merci,
Bien à vous,
Frédéric

**Comment by fredericBregier** [comment]
Note additionnelle: je pensais avec le client Ingest external, bien sûr, pas d'autres clients... ?

**Comment by naddame** [comment]
Bonjour Frédéric,

Pour suivre l'état d'avancement de l'ingest et des workflows ça ne se passe pas dans ingest external.

Voici la documentation de l'API en question :
http://www.programmevitam.fr/ressources/DocCourante/raml/externe/functional-administration.html#operations

Pour le pooling :
Si vous êtes sur java, VITAM offre un client VitamPoolingClient qui utilise AdminExternalClient.
Sinon il faut, côté frontal, continuer à faire des requêtes HEAD sur /admin-external/v1/operations/{request_id} pour suivre l'avancement du workflow.

Bien cordialement
Djamel

**Comment by fredericBregier** [comment]
Bonjour Djamel,
Oui, je me souviens bien des aspects Admin, mais si on imagine un client Ingest sans droit d'admin, comment faire ?
Quelle est la nature de la réponse si on fait un `GET /ingests/{objectId}/archivetransferreply` alors que ce n'est pas prêt ? Un erreur, je suppose, mais laquelle ? Ceci afin de déterminer, par un pooling non "admin" que l'ingest est prêt pour récupérer son ATR...
L'idée ici est d'avoir le résultat sans être autorisé à Admin...
Bien à vous,
Frédéric

**Comment by naddame** [comment]
La réponse normalement est NOT_FOUND (404) mais un GET /ingests/{objectId}/archivetransferreply ne pourra pas être utilisé pour faire du pooling, car avec un workflow en FATAL on aura jamais d'ATR.

Vitam gère la notion d'admin comme suit:
- Le certificat utilisé pour connecter aux external est liée à un contexte Vitam.
- Le contexte Vitam définit un SecurityProfile.
- Le SecurityProfile determine les permissions pour chaque méthode des différentes API external ou peut être full access.

La notion d'admin est maintenant liée aux permission qu'on définit dans le SecurityProfile.

L'api  /admin-external/v1/operations/{request_id}  est annotée :
`@Secured(permission = "operations:id:read:status", description = "Récupérer le code HTTP d'une opération donnée")`

Il faut donc juste avoir la permission `permission = "operations:id:read:status"` dans SecurityProfile  et ça devrait aller.

Il faut noter que  /admin-external/ est exposé sur le port business de jetty.

 
Bien cordialement

**Comment by fredericBregier** [comment]
Merci Djamel !
Je vais partir sur ce 404 et voir ensuite une option pour utiliser le VitamPoolingClient sur cette limitation admin...
Bien à vous !!
