### ISSUE TITLE
Feedback on VM Demo usage

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#20]
Comme promis, mes tests m'ont conduit à trouver quelques points, que j'ai déjà cités sur la VM Démo de Vitam. Voici un court résumé :

**VM (CentOS):**
- la VM sous VirtualBox a tendance à perde son réseau. Un `systemctl restart NetworkManager` fait l'affaire (soit un fix est nécessaire pour LB qui tombe dans la VM, soit un fix de documentation)
    - la commande `systemctl status network.service` retourne

```
network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since ven. 2019-09-20 16:43:39 UTC; 1h 44min left
     Docs: man:systemd-sysv-generator(8)
  Process: 1039 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=1/FAILURE)

sept. 20 16:43:38 vitam-demo systemd[1]: Starting LSB: Bring up/down networking...
sept. 20 16:43:39 vitam-demo network[1039]: Bringing up loopback interface:  [  OK  ]
sept. 20 16:43:39 vitam-demo network[1039]: Bringing up interface enp0s3:  Error: Connection activation failed: No suitable device found for this connection.
sept. 20 16:43:39 vitam-demo network[1039]: [FAILED]
sept. 20 16:43:39 vitam-demo systemd[1]: network.service: control process exited, code=exited status=1
sept. 20 16:43:39 vitam-demo systemd[1]: Failed to start LSB: Bring up/down networking.
sept. 20 16:43:39 vitam-demo systemd[1]: Unit network.service entered failed state.
sept. 20 16:43:39 vitam-demo systemd[1]: network.service failed.
```
   - la commande `systemctl restart NetworkManager` remet la configuration réseau en fonction (pas le network.service). C'est un bug apparemment connu et ancien avec LSB mais je n'ai pas réussi à trouver la cause première, mais juste un contournement. En lançant dès le début ce `systemctl restart NetworkManager`, je n'ai plus de déconnection SSH ou réseau.

Proposition:
- Eventuellement ajouter cette commande à la fin de l'init pour forcer le bon état ?

**Initialisation:**
- En suivant le processus d'initialisation complet, il faut ajouter l'étape d'ajout au tenant des contrats d'accès et d'entrée: ceci mérite un ajout à la documentation
   - Ce point n'a pas fonctionné pendant longtemps pour moi car la modification sur le tenant 1 en tant qu'aadmin provoquait toujours une erreur. Il aura fallu que je me triture les méninges pour comprendre que l'identifiant du fichier ("Identifier":"testrecette", l'identifiant que je pensais devoir mettre pour le contrat d'accès "Name":"Contrat_Acces_Par-Defaut") n'était en rien celui-ci mais un contrat par son code interne (AC-000001). Hélas, les exemples préchargés font référence à des noms qui ne sont pas de cette forme, ce qui perturbe énormément.
     - Il y a confusion entre l'id du contrat (ex: AC-00001) et son identifiant dans le fichier (ex: testrecette). En saisissant testrecette (ou son "name" "Contrat_Acces_Par-Defaut" qui est celui qui est affiché), l'interface IHM Demo est en erreur (rejet de la modification). Avec AC-000001, cela fonctionne.
     - Cette confusion est généralisée car partout ailleurs, c'est par son "nom" qu'il est référencé (comme dans la barre d'accueil). Il en va de même pour le contrat d'entrée bien sûr.
  - Bien sûr, en désactivant la fonction de contrôle comme indiqué en réponse, c'était OK du premier coup et cela m'a permis de continuer mes tests avant de revenir sur la cause première de ce bug.

Proposition:
- Corriger la documentation (je ne pense pas que corriger les identifiants soit une bonne solution ici pour les utilisateurs finaux, mais une documentation claire, et notamment celle de prise en main, est sans doute moins coûteuse et tout autant efficace).

**API:**
- Un comportement d'API que j'aurais trouvé plus cohérent: lorsqu'une resource liée à une opération est demandée (dipexport/id, ingest/id/atr) devrait sans doute tester en interne (ingest-external/access-external) si l'opération existe et est finie d'abord avant de demander la resource résultat. Ainsi, même si le pooling est "la" bonne façon de faire, cela limite les écueils que vous soulignez (resource incomplète si l'opération n'est pas terminée). Il me semble que l'API externe pourrait aussi protéger de certains mauvais usages (pas tous, bien d'accord) mais semblant logiques (pour les développeurs un peu fainéants, **même si l'usage du Pooling est fortement recommandé**).
  - Exemple 1:
`POST /ingests` => retourne un id d'opération d'entrée et un code 202 (ACCEPTED)
`GET /ingests/id/archivetransferreply` => retourne 200 et l'ATR si OK, sinon si non terminé, et donc non existant, il retourne actuellement NOT_FOUND (404), ce qui est correct mais peut aussi s'appliquer à une opération inexistante...

Proposition:
`GET /ingests/id/archivetransferreply` => retourne 200 et l'ATR si OK, sinon si non terminé mais existant, il pourrait retourner 202 ACCEPTED, ce qui est cohérent avec le pooling (suppose que Ingest-external fasse d'abord un HEAD /operation/id pour l'ingest pour répondre 202 si non terminé), réservant ainsi le 404 pour qqc de cohérent.

   - Exemple 2:
`POST /dipexport` => retourne un id d'opération d'export et un code 202 (ACCEPTED)
`GET /dipexport/id/dip` => retourne 200 et le DIP si OK, sinon si non terminé, et donc non existant, il retourne actuellement 200 mais avec un VitamError à NOT_FOUND (404).

Proposition:
`GET /dipexport/id/dip` => retourne 200 et le DIP si OK, sinon si non terminé mais existant, il pourrait retourner 202 ACCEPTED, ce qui est cohérent avec le pooling (suppose que Access-external fasse d'abord un HEAD /operation/id pour l'export pour répondre 202 si non terminé), réservant ainsi le 404 pour qqc de cohérent.

- Quelques erreurs de documentation d'API (surtout les codes retours en cas d'erreur) qui m'ont obligé à lire le code pour trouver les bons tests à effectuer. (je viens de citer les principaux juste avant)

**Comment by croftophile** [comment]
Bonjour,
Question bête : quelle est la version de la VM de démo incriminée ?
Cordialement,
Olivier

**Comment by fredericBregier** [comment]
Pas bête, j'ai oublié de le préciser dans le ticket.
Toujours la même: Vitam 2.6.3-1
Le Host est un Ubuntu 19.04 avec VirtualBox 6.0.12
Bien à vous,
Frédéric

**Comment by fredericBregier** [comment]
Pour information (pour le nouveau DT ;-) ), Waarp-Vitam a été validée grâce à vos aides et à vos VM.
Nous considérons que la V1.0.0 publiée (une annonce officielle suivra bientôt) est opérationnelle pour la mise en production. Bien sûr, si vous souhaitez tester son fonctionnement, et éventuellement voir comment même améliorer son intégration, nous pouvons vous y aider et nous avons quelques idées (comment réduire par exemple le coût HTTP du renvoi du DIP à son minimum). De même si des utilisateurs sont intéressés...

Pour information également, nous demandons le retour de Waarp au SILL:
https://github.com/DISIC/sill/issues/43

Les soucis de réseau signalés dans la 2.6.3-1 semblent avoir disparu dans la 2.11.1.
Les autres points n'étant pas bloquant, nous avons pu finaliser en suivant vos recommandations.
Merci encore,
Bien à vous,
Frédéric
