### ISSUE TITLE
Outil d'architecture ?

### ISSUE THREAD

**Issue by lhauspie** [ProgrammeVitam/vitam#21]
Bonjour,

Je trouve votre documentation assez claire et complète en terme d'architecture (applicative, fonctionnelle, technique, etc.).

Je comprends que vous utilisez une approche "documentation as code" avec la génération par Sphinx... mais vos diagrammes ne semblent pas être "codés".

J'aimerai savoir quel outil vous utilisez pour faire vos diagrammes que je trouve très clairs malgré la complexité du système ?

Merci d'avance.

**Comment by croftophile** [comment]
Bonjour,
Les schémas sont réalisés sous inkscape, généralement.
Cordialement,
Olivier
