### ISSUE TITLE
Download VM Demo 2.11.x

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#24]
2 Questions très courtes :
1) La dernière version publiée est la 2.11.2 mais la VM disponible (en tapant le lien à la main) est la 2.11.1 (http://download.programmevitam.fr/vitam_repository/2.11.1/VM/demo_vitam_2.11.1.ova). Est-ce ok ?
2) La précédente image faisait 3.6 GO, celle-ci semble faire 6.7 Go. Est-ce normal ?
(je n'arrive d'ailleurs pas à aller au bout du téléchargement, cela s'arrête à 3,2 Go environ et l'image semble cassée).

Bien à vous,
Frédéric

**Comment by croftophile** [comment]
Bonjour Frédéric,
Nous sommes en cours de fix...
Cordialement,
Olivier

**Comment by croftophile** [comment]
Re-,
La VM de démo de la dernière bugfix de R11 (2.11.2) est disponible ici : http://download.programmevitam.fr/vitam_repository/2.11.2/VM/demo_vitam_2.11.2.ova
Le fichier est effectivement plus gros, du fait d'un changement technique de méthode de création.
Cordialement,
Olivier

**Comment by fredericBregier** [comment]
Bonjour,
Merci ! J'ai pu la télécharger (2x plus long, forcément ;-) .
Une fois lancée, les adresses de Vitam sont toutes associées à 127.0.0.1 ? Dans la version précédente, cela utilisait l'adresse principale de la VM (il me semble, à moins que je n'ai fait une modification de la configuration, mais je ne m'en souviens pas).
En conséquence, je ne peux pas accéder aux IHM et donc initialiser Vitam (contrats, ...).
Quelle est la procédure à suivre pour changer l'IP de base des services (au moins ceux nécessaires à un accès externe, c'est à dite les IHM, Consul et xxx-external) ?
Bien à vous,
Frédéric

**Comment by fredericBregier** [comment]
Désolé, rectification : en adressant l'adresse sur le port 80, je tombe bien sur l'interface générale et ensuite sur l'IHM demo.
Je me suis perdu sans doute dans les ports...
Je clos cette issue.
Merci encore !!!
