### ISSUE TITLE
Installation de type 'small'

### ISSUE THREAD

**Issue by tibrox** [ProgrammeVitam/vitam#25]
Bonjour,
Pour le contexte : je fais parti du centre de production GED de l'assurance maladie, et je tente l'installation du produit vitam sur une configuration de type 'small' (3 partitions linux + 1 partition pour l'offre de stockage). Ces partitions sont isolées d'internet.

Lors de la commande de déploiement, tout se passe bien sauf la partie 'syslogd' :
TASK [syslogd : ensure rsyslog package is installed] ****************************************************************************************************
FAILED - RETRYING: ensure rsyslog package is installed (1 retries left).
FAILED - RETRYING: ensure rsyslog package is installed (1 retries left).
FAILED - RETRYING: ensure rsyslog package is installed (1 retries left).
FAILED - RETRYING: ensure rsyslog package is installed (1 retries left).
[...]
PLAY RECAP **********************************************************************************************************************************************
152101lpbh                 : ok=12   changed=1    unreachable=0    failed=1    skipped=9    rescued=0    ignored=0
152101lpbi                 : ok=11   changed=1    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0
152101lpbj                 : ok=11   changed=1    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0
152101lpbl                 : ok=15   changed=1    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0

Hors, rsyslog me semble fonctionnel sur la machine.
Comment savoir d'où vient cette erreur ? et comment savoir si l'installation est fonctionnelle ?
D'ailleurs, existe-t-il un forum d'utilisateurs ou d'entraide ?
Merci.

**Comment by vitam-prg** [comment]
Bonjour,

Tout d'abord, désolé du teps de réponse...
le playbook de déploiement de la solution logicielle s'assure que le package rsyslog est présent et interroge (je suppose, pour votre cas) `yum`. Si le package n'existe pas sur un de vos repo, cela plante la tâche.
Pour une meilleure analyse, une trace plus complète est nécessaire.
Cordialement,
Olivier
