### ISSUE TITLE
vitam-storage absent 

### ISSUE THREAD

**Issue by bxaxa** [ProgrammeVitam/vitam#29]
Bonjour,
  quand j'essais de recompiler vitam à partir de ses sources, il manque le product vitam-storage.

`[root@testbxaxa deb]# ls

vitam-external  vitam-product

[root@testbxaxa deb]# pwd

/tmp/vitam/vitam/deb

[root@testbxaxa deb]# grep -ri storage *

[root@testbxaxa deb]#
`

Auriez vous une idée ? Merci

**Comment by vitam-prg** [comment]
Bonjour,
Les propos ci-dessous s'appliquent sur un environnement (si j'ai bien saisi) debian.
Le composant `vitam-storage` n'et pas sous `(racine)/deb/*`, mais à compiler (via maven) depuis le répertoire  `sources`.
La commande à passer est : 
`cd sources && mvn clean package rpm:attached-rpm jdeb:jdeb -f sources/pom.xml -P-vitam`

Cordialement,

Olivier

Cordialement,

**Comment by TDevillechabrolle** [comment]
Petit ménage de confinement dans les issues.
Avez-vous pu surmonter le problème, et dans ce cas je vais clore le ticket, ou est-il toujours présent ?
