### ISSUE TITLE
problème d'installation docker

### ISSUE THREAD

**Issue by akakeronos** [ProgrammeVitam/vitam#30]
Bonjour,
J'essaye d'installer une instance de vitam de démo sur une distribution debian jessie.

J'ai donc suivi la documentation disponible ici https://github.com/ProgrammeVitam/vitam#51alternative-1--docker

Cette documentation est-elle à jour ? Peut-elle être utilisée avec cette distribution ?

Dans les pre-requis il est indiqué qu'un dossier $HOME/.m2 doit être accessible en écriture.
Cependant dans les scripts d'install on trouve mkdir -p /devhome/.m2 (dev-deployment/dev-base/Dockerfile-deb)

Ensuite il est indiqué "Le script demande "Please enter the location of your vitam git repository" (par exemple : /$HOME/git/vitam) ;"

Rien de mon côté lors de l'install

Ensuite lors de l'exécution de la commande vitam-build-repo j'ai l'erreur suivante

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (install node and npm) on project ihm-demo-front: Could not download Node.js: Got error code 401 from the server. -> [Help 1]

Y a t-il d'autres sources de documentation pour procéder à cette installation conteneurisée ?

Merci d'avance

**Comment by vitam-prg** [comment]
Bonjour,
Comme tout, la documentation peut être parfois perfectible...
Nous recommandons, pour les versions les plus récentes de VITAM, de préférer stretch, mais jessie devrait convenir (l'image docker, elle, sera stretch).
Le fameux dossier `.m2` est mappé depuis votre machine DANS le docker ; c'est pour cela que c'est un prérequis.
Effectivement, nous avons apporté des améliorations au script, qui ne pose plus la question, si le script lancé fait bien partie du dépôt git (cf. `dev-deploment/run.sh`)
Concernant `vitam-build-repo`, ce script ne fonctionne **que** en interne du projet. De ce fait, vous subissez une HTTP 401 (_unauthorized_). La documentation vous donne la commande à passer pour builder "hors VITAM" ( commande `maven` avec `-P-vitam` ; la commande complète est `cd /code;mvn clean install  jdeb:jdeb -f sources/pom.xml -P-vitam`). 
A l'issue de cette commande maven,vous aurez produit des deb/rpm, mais... il vous faudra encore lancer 2 shell : 

- `(sous deb ou rpm, selon votre distro)/vitam-product/build-all.sh`

- `(deb ou rpm)/vitam-external/build_repo.sh` ,

 afin de builder des binaires "vitam ready" (lié à des COTS, autrement dit). 

A l'issue, vous pouvez lancer les commandes dans l'ordre `vitam-recreate-repo` (recréation de la base de données associée au repo "local"), puis `vitam-deploy`.

A l'issue, les ports applicatifs des IHM étant mappés, vous pouvez vous connecter ou installer également des "extra" (qui facilitent l'usage de vitam pour les novices), avec la commande `vitam-deploy-extra`. Sera installé, en particulier, un apache reverse proxy qui met à disposition une page d'accueil avec les liens sur les différentes interfaces graphiques.
Avec vos retours, nous tâcherons de mettre à jour la documentation .
Cordialement,

Olivier

**Comment by akakeronos** [comment]
Bonjour,
Merci pour ce retour détaillé.

J'ai lancé la commande maven indiquée et j'ai une nouvelle erreur

Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project fr.gouv.vitam:common-private:jar:2.11.3: Failure to find org.elasticsearch:metrics-elasticsearch-reporter:jar:2.3.0-VITAM in https://repo.maven.apache.org/maven2 

Le paquet a bien l'air présent [ici](https://repo.maven.apache.org/maven2/org/elasticsearch/metrics-elasticsearch-reporter/) mais pas en version 2.3

**Comment by vitam-prg** [comment]
Bonjour,

Effectivement, j'ai oublié de préciser qu'au préalable, il est nécessaire de _builder_ au préalable `elasticsearch-metrics-reporter-java` (version 2.3.0-VITAM https://github.com/ProgrammeVitam/elasticsearch-metrics-reporter-java/tree/2.3.0-VITAM).
Cette étape peut être faite "hors docker" (du fait du mappage du .m2 de votre machine dans le docker).
Pour plus de précisions, vous pouvez vous référer au fichier `README.rst` de vitam (en racine du projet) et à https://github.com/ProgrammeVitam/elasticsearch-metrics-reporter-java/blob/2.3.0-VITAM/README.md

Un dernier point,la version la plus récente de vitam correspond à la branche `master_2.15.x`.
Cordialement,

**Comment by akakeronos** [comment]
Bonjour,
J'ai finalement réussi à déployer une instance de vitam en passant par l'option image virtuelle.
J'ai regardé dans la doc mais je n'ai pas trouvé comment récupérer les identifiants de connexion ou comment les initialiser.
Pourriez-vous m'indiquer où trouver cette information ?

Merci d'avance

**Comment by fredericBregier** [comment]
Bonjour,
Pour vous aider, peut-être vous inspirer de mes notes:
https://github.com/waarp/WaarpVitam/blob/v1.0/WaarpVitamInstall/README.md

En particulier:

See https://www.programmevitam.fr/pages/ressources/

For the demo VM from Vitam:
- Follow the instruction from https://www.programmevitam.fr/ressources/DocCourante/autres/fonctionnel/VITAM_Guide_de_prise_en_main.pdf
- Use the examples files from http://download.programmevitam.fr/vitam_repository/2.6.1/tests/Jeu_de_tests_Guide_de_prise_en_main_R10.zip

In particular:
- Choose your tenant (`9` for the example)
- Connect using the default administrator user

      aadmin/aadmin1234
- Upload Rules referential
- Upload Agents services referential
- Upload Access contract
- Upload Ingest contract

In addition, you should allow those access and ingest contracts or all
permissions for this tenant `9`. To do that:
- Disconnect from tenant `9`
- Reconnect to tenant `1` (administration)
- Go to Admin context referential
- Edit the default one `admin-context` `CT-000001`
   - either Add `AC-000001` access contract and `IC-000001`, `IC-000002`, 
   `IC-000003` ingest contracts to tenant `9`
    - either Change `Activation des permissions` to false
- Save the change

Extra notes:
- Within the Vitam Demo VM, the network sometimes is going down due to a LSB
 error. To remediate, launch from start the following command (under root).:
 
      systemctl restart NetworkManager

**Comment by akakeronos** [comment]
Merci !!

**Comment by nguyenvanduyet** [comment]
can you guide me to setup Vitam development environment when cloning Vitam project on git ?

**Comment by TDevillechabrolle** [comment]
> can you guide me to setup Vitam development environment when cloning Vitam project on git ?

Can you open a distinct issue please ? this one is closed

**Comment by nguyenvanduyet** [comment]
i want to build project Vitam . I cloned on git https://github.com/ProgrammeVitam/vitam#alternative-1-docker but it didn't work even though I followed the instructions below. can you guide me the steps to get it running? thanks

**Comment by NKDuy889** [comment]
can vitam still be used?

**Comment by TDevillechabrolle** [comment]
Yep, we published our 4th version earlier this year, and the 5th.rc will be released this fall.
Please, open another issue to exchange ;-)

**Comment by NKDuy889** [comment]
i deploy project to docker but i didn't go in to any port. Can't you tell me how to fix this?

**Comment by bangot** [comment]
please link the exact instructions to build vitam, with video the better .thank you

**Comment by bangot** [comment]
ăn lol nhé

**Comment by bangot** [comment]
please link the exact instructions to build vitam, with video the better .thank you

**Comment by TDevillechabrolle** [comment]
Bạn có thể mở một vé chuyên dụng được không?

**Comment by bangot** [comment]
What do you mean by what you say?

**Comment by bangot** [comment]
i don't understand what you mean

**Comment by TDevillechabrolle** [comment]
I tried to ask you to open a new dedicated issue. This one is closed

**Comment by bangot** [comment]
please utraviewer help me

**Comment by bangot** [comment]
ie can this vitamin bend?

**Comment by bangot** [comment]
i.e. can this vitamin still be used?

**Comment by bangot** [comment]
ie this program vit can still use you?

**Comment by bangot** [comment]
ie this program vit can still use you?

**Comment by bangot** [comment]
i.e. is this program still usable?

**Comment by NKDuy889** [comment]
how can't i fix this : 
java: package fr.gouv.culture.archivesdefrance.seda.v2 does not exist
