### ISSUE TITLE
http://download.programmevitam.fr/ unavailable

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#33]
Hello,
Quand j'essaie d'accéder aux jars de la distribution via le site de download, j'obtiens:

     Error 503 Unavailable, the server is paused.
     Unavailable, the server is paused.
     Varnish cache server

**Comment by TDevillechabrolle** [comment]
Bonjour,
Nous avons un petit souci avec l'hébergement du site download.
On essaie de remettre ça en état au plus tôt.

Bonne journée.

**Comment by TDevillechabrolle** [comment]
@fredericBregier le site doit être de nouveau accessible.
Bonne soirée !

**Comment by fredericBregier** [comment]
Merci ;-)
