### ISSUE TITLE
Updating author list

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#34]
Could be nice to update the list of author to include old friends...

**Comment by fredericBregier** [comment]
Bientôt 3 semaines et aucun retour sur cette demande légitime ?

**Comment by fredericBregier** [comment]
Si pas clair: il manque un nom dans les participants... n'est-il pas ?

**Comment by fredericBregier** [comment]
Nice reminder on this issue (would be nice) ;-)

**Comment by TDevillechabrolle** [comment]
Noted

**Comment by TDevillechabrolle** [comment]
Done in latest release :-)

**Comment by fredericBregier** [comment]
Thank you !!
