### ISSUE TITLE
When is code going to be released?

### ISSUE THREAD

**Issue by jck1307** [ProgrammeVitam/vitam#4]
Hello,
your project is great but your code isn't up-to-date...

Are you going to release it soon? and open it really?

Thanks,

JC

**Comment by JSLair** [comment]
Hi,

Thank you for your interest in our solution. VITAM is an open source project, as the entire code and tests tools are released under open licenses. Version 1.0 was just released, and more features are still under way.

But as it is stated in the CONTRIBUTING.md, it doesn't currently follows an "open development" model ; therefore, code releases follow our internal release cycles. We thrive to have a more open development model, and it is certainly one of our long-terme goals, but it isn’t the currently chosen governance model for our project.

Please be welcome to get in touch with us (contact@programmevitam.fr) if you have more questions or want to propose contributions !
