### ISSUE TITLE
Version number ?

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#40]
Les dernières versions semblent chaotiquement numérotées, peut-être pourriez-vous préciser ?

- 2.1.19 (et la dernière 2.1.21)
- 2.15.3 : est-ce bien une version > 2.1 ? Mais dans ce cas, pourquoi pas de 2.17, 2.19, ... ? alors que la 2.1 (LTS ?) en connaît ?
- 3.0.2 : celle-là, c'est clair : rupture y compris de compatibilité avec les 2.X

Merci de préciser votre logique car cela aidera ceux qui veulent apporter leur support à bien rester dans les clous

**Comment by gansheer** [comment]
Bonjour,

Des informations sur les version sont disponibles dans la [documentation des montées de versions](https://www.programmevitam.fr/ressources/DocCourante/html/migration/index.html).

Pour rappel seule une version mineure sur 5 (soit tous les 5 sprints de développement) fait l'objet d'une release officielle. Ensuite nous ne faisons théoriquement que des bugfix sur ces version mineures.

**Comment by fredericBregier** [comment]
Merci Gaëlle !
