### ISSUE TITLE
Issue on Repository version 3.0.2: checksum incorrect

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#43]
Downloading from Vitam repository: http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/access-external-api/3.0.2/access-external-api-3.0.2.pom
     [WARNING] Checksum validation failed, expected 397088447fef0c414b209a8d7653de644d39e7be but is d7e6b232974fc13d3f9efd6833e398ff31c6bc23 from Vitam repository for http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/access-external-api/3.0.2/access-external-api-3.0.2.pom
     [WARNING] Could not validate integrity of download from http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/access-external-api/3.0.2/access-external-api-3.0.2.pom: Checksum validation failed, expected 397088447fef0c414b209a8d7653de644d39e7be but is d7e6b232974fc13d3f9efd6833e398ff31c6bc23
     [WARNING] Checksum validation failed, expected 397088447fef0c414b209a8d7653de644d39e7be but is d7e6b232974fc13d3f9efd6833e398ff31c6bc23 from Vitam repository for http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/access-external-api/3.0.2/access-external-api-3.0.2.pom

**Comment by fredericBregier** [comment]
Other examples:
- v3.0.1

      Downloading from Vitam repository: http://download.programmevitam.fr/vitam_repository/3.0.1/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.1/ingest-external-client-3.0.1.pom
      Downloaded from Vitam repository: http://download.programmevitam.fr/vitam_repository/3.0.1/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.1/ingest-external-client-3.0.1.pom (2.2 kB at 1.6 kB/s)

- v3.0.2

      Downloading from Vitam repository: http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.2/ingest-external-client-3.0.2.pom
      [WARNING] Checksum validation failed, expected ecb9311cfddb7b56ce6508901f907f2fca2fc29a but is 153e7196d3bc428bb60fd2c60d52c9cdf4136606 from Vitam repository for http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.2/ingest-external-client-3.0.2.pom
      [WARNING] Could not validate integrity of download from http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.2/ingest-external-client-3.0.2.pom: Checksum validation failed, expected ecb9311cfddb7b56ce6508901f907f2fca2fc29a but is 153e7196d3bc428bb60fd2c60d52c9cdf4136606
      [WARNING] Checksum validation failed, expected ecb9311cfddb7b56ce6508901f907f2fca2fc29a but is 153e7196d3bc428bb60fd2c60d52c9cdf4136606 from Vitam repository for http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.2/ingest-external-client-3.0.2.pom
      Downloaded from Vitam repository: http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/fr/gouv/vitam/ingest-external-client/3.0.2/ingest-external-client-3.0.2.pom (2.3 kB at 4.6 kB/s)

**Comment by croftophile** [comment]
On fixe ASAP

**Comment by fredericBregier** [comment]
Thanks ;-)

**Comment by croftophile** [comment]
Re-,
Vous ne devriez plus rencontrer l'erreur.
Cordialement,
Olivier

**Comment by fredericBregier** [comment]
Yep !!! Merci !!
