### ISSUE TITLE
Version 3.0.3-1 Maven site link

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#47]
Hello,
J'ai vu sur votre site que la version 3.0.3-1 serait disponible, mais seule le lien pour la version 3.0.2 semble fonctionner sur le dépôt Maven : http://download.programmevitam.fr/vitam_repository/3.0.2/mvn_repo/

Sur votre site, vous indiquez https://r13.env.programmevitam.fr/ mais ce lien est soumis à une authentification.

Comment devons-nous procéder ?
Bien à vous,
Frédéric Brégier

**Comment by TDevillechabrolle** [comment]
Bonjour Frédéric,

Le repo a été mis à jour:
https://download.programmevitam.fr/vitam_repository/3.0.3-1/

Est-ce que cela correspond à ce que vous cherchiez ?

Thierry

**Comment by fredericBregier** [comment]
En effet, c'est bon.
Merci
