### ISSUE TITLE
Demande d'information

### ISSUE THREAD

**Issue by bbouchen** [ProgrammeVitam/vitam#5]
Bonjour
Je me permets d'ouvrir un ticket sur le projet, je m’intéresse à la solution dans le cadre de l'un de mes projets, je n 'ai pas réussi à comprendre le système de stockage des documents.
Il est possible de déléguer le stockage à une solution tierce mais il est aussi possible de le faire localement
Vous me confirmez que les documents ne sont pas stockés dans mongo db ?
quel est le rôle du module storage engine ?
Merci pour votre réponse

**Comment by fredericBregier** [comment]
Les documents ne sont pas stockés dans MongoDB. Ils le sont dans des offres techniques de stockage (de type CEPH ou équivalent). Le rôle du Storage Engine est de faire le lien entre Vitam et les offres de stockages.

Par exemple, il peut avoir un client CEPH, SWIFT, ou le client de l'implémentation "limitée" (quelques centaines de To) dite "locale" (il s'agit d'un serveur hébergeant du disque soit local soit via SAN mais dédié).

Le Storage Engine a la responsabilité de s'assurer que les offres (par défaut 3) ont bien écrit les fichiers (3 copies donc) et assure les réplications lui-même. Mais il est possible de changer la façon dont cela s'opère par exemple si l'offre dispose déjà de copies assurées et fiables en délestant donc de cette opération (au moins pour 2 copies) le moteur de stockage. Pour des raisons de sécurité, il est conseillé de ne pas avoir 3 fois la même offre (ou 1 seule distribuant sur 3 stockages similaires) afin d'éviter les effets de bord d'attaques potentielles ou de corruptions.

**Comment by azizdenice** [comment]
Bonjour, je suis nouveau dans le programme, je viens d'installer la VM et les api sur postman, toutefois j'arrive pas à me connecter apparament faute de certificats manquant, je voudrais bien savoir où je pourrais trouver ces certificats si possible.
Merci d'avance
![image](https://user-images.githubusercontent.com/6890188/66464006-7e76bb00-ea7e-11e9-99d1-5183a58623fe.png)
