### ISSUE TITLE
Maven repo for 3.6.0 innaccessible

### ISSUE THREAD

**Issue by fredericBregier** [ProgrammeVitam/vitam#50]
Cette URL ne répond pas : http://download.programmevitam.fr/vitam_repository/3.6.0/mvn_repo/
(la dernière qui marchait était : http://download.programmevitam.fr/vitam_repository/3.0.3-1/mvn_repo/

Question annexe : pourquoi on passe de la version 3.0.3 (R13) à la version 3.6.0 (R14) ? Je n'ai pourtant pas, je crois, manqué de versions ?

**Comment by agrippon** [comment]
Bonjour Frédéric
Nous en avons en effet subi ces derniers jours des problèmes d'infrastructure qui empêchent l'accès à certaines URL, nous travaillons dessus mais nous dépendons aussi d'autres acteurs.
Pour les versions, pouvez-nous préciser la question ? car cela nous est arrivé avant de passer par exemple de 2.11.x à 2.15.x avec des versions non publiées correspondant aux différentes itérations.
Bonne journée,
Alice Grippon

**Comment by fredericBregier** [comment]
Bonjour Alice, 
En effet, j'aurais dû m'en douter... J'ai oublié les itérations intermédiaires (perturbant pour qq1 d'extérieur qui ne les voit pas).
Merci !
J'attends votre feu vert pour pouvoir tester le dépôt maven. 
Bien à vous, 
Frédéric

**Comment by agrippon** [comment]
Bonjour Frédéric
Le site fonctionne (enfin)... 
Bonne journée
Alice
