### ISSUE TITLE
INSTALLATION DE VITAM PROBLEME  APT UPDATE

### ISSUE THREAD

**Issue by nknb** [ProgrammeVitam/vitam#51]
bonsoir ,
depuis un moment j'arrive plus a accéder au dépôt de Vitam.
Lorsque je fais un update j'ai le message suivant: 
root@VITAM:/home/luc# apt update
Atteint :1 http://deb.debian.org/debian buster InRelease
Atteint :2 http://ppa.launchpad.net/ansible/ansible/ubuntu trusty InRelease
Réception de :3 http://ftp.debian.org/debian stretch-backports InRelease [91,8 k                                                                                                                B]
Réception de :4 http://deb.debian.org/debian-security buster/updates InRelease [                                                                                                                65,4 kB]
Réception de :5 http://deb.debian.org/debian buster-updates InRelease [51,9 kB]
Réception de :6 http://deb.debian.org/debian buster-backports InRelease [46,7 kB                                                                                                                ]
Ign :7 http://deb.debian.org/debian stretch InRelease
Atteint :8 http://deb.debian.org/debian stretch Release
Réception de :9 http://deb.debian.org/debian-security buster/updates/main Source                                                                                                                s [131 kB]
Réception de :10 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [213 kB]
Réception de :11 http://ftp.debian.org/debian stretch-backports/main Sources.diff/Index [27,8 kB]
Réception de :12 http://ftp.debian.org/debian stretch-backports/main amd64 Packages.diff/Index [27,8 kB]
Réception de :13 http://ftp.debian.org/debian stretch-backports/main Translation-en.diff/Index [27,8 kB]
Réception de :14 http://ftp.debian.org/debian stretch-backports/main Sources 2020-07-22-2003.16.pdiff [1 373 B]
Réception de :15 http://ftp.debian.org/debian stretch-backports/main amd64 Packages 2020-07-22-2003.16.pdiff [767 B]
Réception de :16 http://ftp.debian.org/debian stretch-backports/main amd64 Packages 2020-07-23-0813.21.pdiff [313 B]
Réception de :14 http://ftp.debian.org/debian stretch-backports/main Sources 2020-07-22-2003.16.pdiff [1 373 B]
Réception de :17 http://deb.debian.org/debian buster-backports/contrib Sources.diff/Index [20,9 kB]
Réception de :16 http://ftp.debian.org/debian stretch-backports/main amd64 Packages 2020-07-23-0813.21.pdiff [313 B]
Réception de :19 http://deb.debian.org/debian buster-backports/main Sources.diff/Index [27,8 kB]
Réception de :20 http://deb.debian.org/debian buster-backports/main amd64 Packages.diff/Index [27,8 kB]
Réception de :21 http://deb.debian.org/debian buster-backports/main Translation-en.diff/Index [27,8 kB]
Réception de :22 http://deb.debian.org/debian buster-backports/contrib amd64 Packages.diff/Index [16,5 kB]
Réception de :23 http://deb.debian.org/debian buster-backports/contrib Translation-en.diff/Index [9 592 B]
Réception de :24 http://ftp.debian.org/debian stretch-backports/main Translation-en 2020-07-22-2003.16.pdiff [462 B]
Réception de :24 http://ftp.debian.org/debian stretch-backports/main Translation-en 2020-07-22-2003.16.pdiff [462 B]
Réception de :25 http://deb.debian.org/debian buster-backports/contrib Sources 2020-07-22-2003.16.pdiff [592 B]
Réception de :25 http://deb.debian.org/debian buster-backports/contrib Sources 2020-07-22-2003.16.pdiff [592 B]
Réception de :26 http://deb.debian.org/debian buster-backports/main Sources 2020-07-21-2002.21.pdiff [31 B]
Réception de :27 http://deb.debian.org/debian buster-backports/main Sources 2020-07-22-0202.50.pdiff [639 B]
Réception de :28 http://deb.debian.org/debian buster-backports/main Sources 2020-07-22-0807.38.pdiff [1 080 B]
Réception de :29 http://deb.debian.org/debian buster-backports/main Sources 2020-07-22-1402.55.pdiff [2 633 B]
Réception de :30 http://deb.debian.org/debian buster-backports/main Sources 2020-07-22-2003.16.pdiff [7 952 B]
Réception de :31 http://deb.debian.org/debian buster-backports/main Sources 2020-07-23-0813.21.pdiff [630 B]
Réception de :32 http://deb.debian.org/debian buster-backports/main Sources 2020-07-23-1414.05.pdiff [1 462 B]
Réception de :32 http://deb.debian.org/debian buster-backports/main Sources 2020-07-23-1414.05.pdiff [1 462 B]
Réception de :33 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-21-2002.21.pdiff [223 B]
Réception de :34 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-22-0807.38.pdiff [194 B]
Réception de :35 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-22-1402.55.pdiff [502 B]
Réception de :36 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-22-2003.16.pdiff [8 271 B]
Réception de :37 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-23-0813.21.pdiff [2 334 B]
Réception de :38 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-23-1414.05.pdiff [1 368 B]
Réception de :39 http://deb.debian.org/debian buster-backports/main Translation-en 2020-07-21-2002.21.pdiff [402 B]
Réception de :38 http://deb.debian.org/debian buster-backports/main amd64 Packages 2020-07-23-1414.05.pdiff [1 368 B]
Réception de :40 http://deb.debian.org/debian buster-backports/main Translation-en 2020-07-22-2003.16.pdiff [13,2 kB]
Réception de :41 http://deb.debian.org/debian buster-backports/main Translation-en 2020-07-23-1414.05.pdiff [233 B]
Réception de :41 http://deb.debian.org/debian buster-backports/main Translation-en 2020-07-23-1414.05.pdiff [233 B]
Réception de :42 http://deb.debian.org/debian buster-backports/contrib amd64 Packages 2020-07-22-2003.16.pdiff [689 B]
Réception de :43 http://deb.debian.org/debian buster-backports/contrib Translation-en 2020-07-22-2003.16.pdiff [617 B]
Réception de :43 http://deb.debian.org/debian buster-backports/contrib Translation-en 2020-07-22-2003.16.pdiff [617 B]
Réception de :42 http://deb.debian.org/debian buster-backports/contrib amd64 Packages 2020-07-22-2003.16.pdiff [689 B]
Err :44 https://download.programmevitam.fr/vitam_repository/3.0.2/deb/vitam-product ./ InRelease
  Connexion à download.programmevitam.fr: 443 (192.134.136.84) impossible, délai de connexion dépassé
Err :45 https://download.programmevitam.fr/vitam_repository/3.0.2/deb/vitam-external ./ InRelease
  Impossible de se connecter à download.programmevitam.fr:https :
Err :46 https://download.programmevitam.fr/vitam_griffins/1.14.0/deb ./ InRelease
  Impossible de se connecter à download.programmevitam.fr:https :
859 ko réceptionnés en 31s (28,0 ko/s)
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
1 paquet peut être mis à jour. Exécutez « apt list --upgradable » pour le voir.
W: Impossible de récupérer https://download.programmevitam.fr/vitam_repository/3.0.2/deb/vitam-product/./InRelease  Connexion à download.programmevitam.fr: 443 (192.134.136.84) impossible, délai de connexion dépassé
W: Impossible de récupérer https://download.programmevitam.fr/vitam_repository/3.0.2/deb/vitam-external/./InRelease  Impossible de se connecter à download.programmevitam.fr:https :
W: Impossible de récupérer https://download.programmevitam.fr/vitam_griffins/1.14.0/deb/./InRelease  Impossible de se connecter à download.programmevitam.fr:https :
W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

SVP ,j'ai besoin d'aide .
Je tiens a préciser q'avant  le Update marchais sans problème.

**Comment by TDevillechabrolle** [comment]
Bonjour,

Notre hébergeur a subit des problèmes d'infrastructure impactant la disponibilité de https://download.programmevitam.fr
A priori, tout est revenu dans l'ordre.

Pouvez-vous me confirmer que vous pouvez à nouveau accéder aux repositories ?

Thierry
