### ISSUE TITLE
Impossible de construire VITAM

### ISSUE THREAD

**Issue by PhilippeKerrest** [ProgrammeVitam/vitam#87]
Bonjour,
J'essaie de construire VITAM, mais sans succès ...

J'ai tenté ça :

[everteam@zkhost ~]$ cat /etc/redhat-release 
**CentOS Linux release 7.9.2009** (Core)

[everteam@zkhost ~]$ mvn --version
**Apache Maven 3.8.1** (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/src/apache-maven
Java version: 11.0.10, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1127.el7.x86_64", arch: "amd64", family: "unix"

[everteam@zkhost ~]$ java -version
**openjdk version "11.0.10" 2021-01-19 LTS**
OpenJDK Runtime Environment 18.9 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9-LTS, mixed mode, sharing)

[everteam@zkhost ~]$ **git clone --branch 3.0.15 https://github.com/ProgrammeVitam/vitam.git**

[everteam@zkhost ~]$ git clone https://github.com/ProgrammeVitam/elasticsearch-metrics-reporter-java.git
[everteam@zkhost ~]$ cd elasticsearch-metrics-reporter-java/
[everteam@zkhost ~]$ mvn clean install

[everteam@zkhost ~]$ cd ~/vitam

[everteam@zkhost ~]$ mvn package rpm:attached-rpm jdeb:jdeb install -f sources/pom.xml -P-vitam

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for vitam-parent 3.0.15:
[INFO] 
[INFO] vitam-parent ....................................... SUCCESS [  1.679 s]
[INFO] common ............................................. SUCCESS [  0.057 s]
[INFO] common-public ...................................... SUCCESS [ 32.303 s]
[INFO] common-http-interface .............................. SUCCESS [  6.011 s]
[INFO] Common for Junit ................................... SUCCESS [ 42.640 s]
[INFO] common-private ..................................... SUCCESS [01:59 min]
[INFO] Common Database Vitam .............................. SUCCESS [  0.062 s]
[INFO] Common Database Public ............................. SUCCESS [ 14.966 s]
[INFO] Common Database Private ............................ FAILURE [28:27 min]

Il y a plein d'exceptions ... mais avant d'entrer dans le détail je voulais savoir si j'avais une chance d'y arriver comme je l'ai fait.
Merci pour votre aide.

**Comment by TDevillechabrolle** [comment]
Bonjour Philppe,

Je vais soumettre ça à nos équipes.
Une raison particulière vous amène à construire les rpms plutôt que d'utiliser ceux que nous produisons et mettons à disposition ici ?
https://download.programmevitam.fr/vitam_repository/3.0.15/

Bonne journée
Thierry
